name: React deployment with artifact
on:
  push:
    branches:
      - main
jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - name: Get the context
        run: echo "${{ toJSON(github.event) }}"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-module-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      output_value: ${{ steps.output_id.outputs.output_file }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-module-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Publishing the JS file as output
        id: output_id
        run: find dist/assets/*.js -type f -execdir echo 'output_file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Display the output from build job
        run: echo ${{ needs.build.outputs.output_value }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Listing the artifact
        run: ls -l
      - name: Deploy
        run: echo "Deploying ..."